# .github/workflows/deploy_scraper.yml
name: CI/CD — Build & Deploy Scraper Lambda Image

on:
  push:
    branches: [ main ]
    paths:
      - 'main_scraper/**'
      - 'scrapers/**'
      - '.github/workflows/deploy_scraper.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials for S3, ECR & Lambda
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            eu-central-1

      # 3. Fetch headless-chrome and chromedriver from S3 into build context
      - name: Download headless-chrome from S3
        run: |
          mkdir -p main_scraper/bin/chrome-linux64
          aws s3 cp \
            s3://stagehop-lambda-dependencies/bin/chrome-linux64/ \
            main_scraper/bin/chrome-linux64/ \
            --recursive \
            --region eu-central-1
          chmod +x main_scraper/bin/chrome-linux64/chrome
      - name: Download chromedriver from S3
        run: |
          aws s3 cp \
            s3://stagehop-lambda-dependencies/bin/chromedriver \
            main_scraper/bin/chromedriver --region eu-central-1
          chmod +x main_scraper/bin/chromedriver
          
      # 4. Log in to your ECR registry
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 \
            | docker login --username AWS --password-stdin 251995574407.dkr.ecr.eu-central-1.amazonaws.com
      # 5. Build, tag, and push the Docker image
      - name: Build & push Docker image
        run: |
          IMAGE=251995574407.dkr.ecr.eu-central-1.amazonaws.com/scraper-lambda-repo:latest
          docker build -t scraper-lambda -f main_scraper/dockerfile .
          docker tag scraper-lambda:latest $IMAGE
          docker push $IMAGE

          docker run --rm $IMAGE bash -lc "\
          echo '→ Chrome:' \$((/usr/local/bin/chrome-linux64/chrome --version) 2>&1); \
          echo '→ Driver:' \$((/usr/local/bin/chromedriver --version) 2>&1)"
          docker run --rm $IMAGE bash -lc "\
            ldd /usr/local/bin/chrome-linux64/chrome | grep 'not found' || echo 'Chrome all libs OK'; \
            ldd /usr/local/bin/chromedriver | grep 'not found' || echo 'Driver all libs OK'"
          docker run --rm $IMAGE bash -lc "\
            /usr/local/bin/chrome-linux64/chrome \
              --headless=new --no-sandbox --disable-setuid-sandbox \
              --disable-dev-shm-usage --dump-dom https://example.com \
            || echo 'HEADLESS FAIL';"
            
      # 6. Update Lambda to use the new image
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name scraper-lambda \
            --region eu-central-1 \
            --image-uri 251995574407.dkr.ecr.eu-central-1.amazonaws.com/scraper-lambda-repo:latest \
            --publish
