name: CI/CD — Test, Build & Deploy Scraper Lambda Image

on:
  push:
    branches: [ main ]
    paths:
      - 'main_scraper/**'
      - 'scrapers/**'
      - 'tests/**'
      - '.github/workflows/deploy_scraper.yml'

jobs:
  test-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS creds (so we can pull from S3)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            eu-central-1

      # 3. Fetch headless-chromium + chromedriver from S3
      - name: Prepare Chrome binaries
        run: |
          mkdir -p main_scraper/bin
          aws s3 cp \
            s3://stagehop-lambda-dependencies/bin/headless-chromium \
            main_scraper/bin/headless-chromium
          aws s3 cp \
            s3://stagehop-lambda-dependencies/bin/chromedriver \
            main_scraper/bin/chromedriver
          chmod +x main_scraper/bin/{headless-chromium,chromedriver}

      # 4. Set up Python and run tests (with Chrome available)
      - name: Set up Python & run pytest
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
        env:
          PYTHONPATH: ${{ github.workspace }}
          PATH: main_scraper/bin:/usr/local/bin:${{ env.PATH }}
          CHROME_BIN: main_scraper/bin/headless-chromium
        run: |
          python -m pip install --upgrade pip
          pip install -r main_scraper/requirements.txt pytest selenium
          pytest --maxfail=1 --disable-warnings -q

      # 5. Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 \
            | docker login --username AWS --password-stdin 251995574407.dkr.ecr.eu-central-1.amazonaws.com

      # 6. Build, tag, and push the Docker image
      - name: Build & push Docker image
        run: |
          IMAGE_URI=251995574407.dkr.ecr.eu-central-1.amazonaws.com/scraper-lambda-repo:latest
          docker build -t scraper-lambda -f main_scraper/dockerfile .
          docker tag scraper-lambda:latest $IMAGE_URI
          docker push $IMAGE_URI

      # 7. Deploy to Lambda
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name scraper-lambda \
            --region eu-central-1 \
            --image-uri 251995574407.dkr.ecr.eu-central-1.amazonaws.com/scraper-lambda-repo:latest \
            --publish
