name: Deploy Scraper Lambda

on:
  push:
    branches: [ main ]
    paths:
      - 'main_scraper/**'
      - 'tests/**'
      - '.github/workflows/deploy_scraper.yml'

jobs:
  test-and-deploy-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & pytest
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | \
          docker login --username AWS --password-stdin 251995574407.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build & push scraper image
        run: |
          docker build -t scraper-lambda -f main_scraper/dockerfile .
          docker tag scraper-lambda:latest 251995574407.dkr.ecr.eu-central-1.amazonaws.com/scraper-lambda-repo:latest
          docker push 251995574407.dkr.ecr.eu-central-1.amazonaws.com/scraper-lambda-repo:latest

      - name: Deploy scraper Lambda
        run: |
          aws lambda update-function-code \
            --function-name scraper-lambda \
            --image-uri 251995574407.dkr.ecr.eu-central-1.amazonaws.com/scraper-lambda-repo:latest \
            --publish
